# Generated by Django 3.0.2 on 2020-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st',
            name='price',
            field=models.TextField(verbose_name='Станок'),
        ),
    ]
