# Generated by Django 3.0.2 on 2020-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200211_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st',
            name='image',
        ),
        migrations.AlterField(
            model_name='st',
            name='price',
            field=models.CharField(max_length=40, verbose_name='Станок'),
        ),
    ]
