# Generated by Django 3.0.2 on 2020-02-17 17:14

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200216_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='st',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
